kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ingressRoute.yaml
  - provisioning/datasources.yaml

helmCharts:
  - name: grafana-operator
    version: 4.7.5
    repo: https://charts.bitnami.com/bitnami
    releaseName: grafana-operator
    namespace: monitoring
    valuesFile: values.yaml
