version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./config:/etc/nginx/conf.d
    restart: always
    network_mode: bridge