##############################################################################################
# docker-compose for ingress-nginx (revers proxy)                                            #
# configuration can be found in the config folder                                            #
##############################################################################################

version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "3001:3001"
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
      - ./apps/lan_dashboard_build:/usr/share/nginx/html/lan_dashboard:ro
      # - ./docker-setup/html/app2:/usr/share/nginx/html/app2:ro
    restart: always
    networks:
      custom_bridge:
        ipv4_address: 188.20.0.2

networks:
  custom_bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 188.20.0.0/16