kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ingressRoute.yaml

helmCharts:
  - name: pihole
    version: 2.27.0
    repo: https://mojo2600.github.io/pihole-kubernetes/
    releaseName: pihole
    namespace: pihole
    valuesFile: values.yaml
