apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: pihole
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      name: http
    - port: 53
      targetPort: 53
      nodePort: 30053
      protocol: UDP
      name: dns
  selector:
    app: pihole