services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: postgres
      GF_SECURITY_ADMIN_PASSWORD: postgres
      GF_PROVISIONING_PATH: /etc/grafana/provisioning
    # volumes:
    #   - ./setup/grafana/dashboards:/etc/grafana/provisioning/dashboards
    #   - ./setup/grafana/datasources:/etc/grafana/provisioning/datasources