apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    dashboards: "grafana"
spec:
  datasource:
    name: Prometheus
    type: prometheus
    url: http://prometheus-operated:9090
    access: proxy
    isDefault: true
  resyncPeriod: 5s
  instanceSelector:
    matchLabels:
      app.kubernetes.io/instance: "grafana-operator"
