auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  # log_level: debug

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 1h       # Any chunk not receiving new logs in this time will be flushed
  max_chunk_age: 1h           # Chunks will be flushed after no more than this time
  chunk_target_size: 1048576  # Aim to build chunks up to approximately this many bytes
  chunk_retain_period: 30s    # Must be greater than the prometheus scrape interval
  max_transfer_retries: 0     # Chunk transfers disabled
  wal:
    dir: "/tmp/wal"

schema_config:
  configs:
  - from: 2020-10-24
    store: boltdb-shipper
    object_store: filesystem
    schema: v11
    index:
      prefix: index_
      period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0s  # No limit

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s
