server:
  http_listen_port: 9080
  grpc_listen_port: 0
  # log_level: debug

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: 'docker'
    # pipeline_stages:
    #   - docker: {}
    #   - json:
    #       expressions:
    #         log: message
    #         time: time
    #         level: level
    #   - timestamp:
    #       source: time
    #       format: 'RFC3339'
    #   - labels:
    #       level:
    #   - output:
    #       source: log
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log
