apiVersion: 1

datasources:
  - name: Prometheus_export
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus_export:9090
    isDefault: true
    version: 1
    editable: true
  - name: Prometheus_import
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus_import:9090
    version: 1
    editable: true
