apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-world-task
  namespace: tekton-pipelines
spec:
  steps:
    - name: echo
      image: ubuntu
      script: |
        #!/bin/bash
        echo "Hello World"
