apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-kube-prometheus-operator
spec:
  steps:
    - name: clone-repo
      image: alpine/git
      script: |
        git clone https://github.com/prometheus-operator/kube-prometheus.git /workspace/kube-prometheus

    - name: apply-manifests
      image: bitnami/kubectl
      script: |
        kubectl apply --filename /workspace/kube-prometheus/manifests/setup
        sleep 10
        until kubectl get servicemonitors --all-namespaces ; do sleep 5; done
        kubectl apply --filename /workspace/kube-prometheus/manifests/
