{
 "title": "Otel Collector - Basic",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "otel_collector",
    "query": {
     "query": "label_values(otelcol_rpc_server_request_size_sum,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "otelcol_process_uptime_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Imported Jobs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"$otel_collector\", exported_job!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exported Scrape Jobs",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "up{exported_job!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Receiver",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Receiver Metrics Points Total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(otelcol_receiver_accepted_metric_points_total{job=\"$otel_collector\"}[1m])",
       "legendFormat": "exporter \"{{receiver}}\" success"
      },
      {
       "expr": "rate(otelcol_receiver_refused_metric_points_total{job=\"$otel_collector\"}[1m])",
       "legendFormat": "exporter \"{{receiver}}\" refused"
      }
     ]
    }
   ]
  },
  {
   "title": "Exporters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exported Metrics Points Total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(otelcol_exporter_sent_metric_points_total{job=\"$otel_collector\"}[1m])",
       "legendFormat": "exporter \"{{exporter}}\" success"
      },
      {
       "expr": "rate(otelcol_exporter_send_failed_metric_points_total{job=\"$otel_collector\"}[1m])",
       "legendFormat": "exporter \"{{exporter}}\" failed"
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(otelcol_process_cpu_seconds_total{job=\"$otel_collector\"}[5m])\r\n",
       "legendFormat": "cpu seconds total"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "otelcol_process_memory_rss{job=\"$otel_collector\"}",
       "legendFormat": "memory"
      }
     ]
    }
   ]
  }
 ]
}