version: '3'

services:

  keycloak:
    image: bitnami/keycloak:latest
    container_name: keycloak
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # KEYCLOAK_HTTP_PORT: 8080
      KEYCLOAK_DATABASE_VENDOR: H2
    networks:
      raspi_docker_custom_bridge:
        ipv4_address: 188.20.0.71
    restart: unless-stopped

networks:
  raspi_docker_custom_bridge:
    external: true
