services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: postgres
      GF_SECURITY_ADMIN_PASSWORD: postgres
      GF_PROVISIONING_PATH: /etc/grafana/provisioning
    networks:
      custom_bridge:
        ipv4_address: 172.20.0.3
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      custom_bridge:
        ipv4_address: 172.20.0.4
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  exporter_node:
    image: prom/node-exporter
    container_name: exporter_node
    pid: "host"
    networks:
      custom_bridge:
        ipv4_address: 172.20.0.5
    volumes:
      - "/:/host:ro,rslave"
    command:
      - '--path.rootfs=/host'
    restart: always

  exporter_jmx:
    image: local/jmx-exporter:1.11
    container_name: exporter_jmx
    ports:
      - "5556:5556"
    volumes:
      - ./jmx-exporter/jmx-exporter-config.yaml:/config/jmx-exporter-config.yaml
      - ./jmx-exporter/logging.properties:/config/logging.properties
    command:
      - java
      - -Djava.util.logging.config.file=/config/logging.properties
      - -jar
      - /jmx_prometheus_httpserver.jar
      - '5556'
      - /config/jmx-exporter-config.yaml
    environment:
      - JMX_URL=service:jmx:rmi:///jndi/rmi://kafka1:9099/jmxrmi
    networks:
      custom_bridge:
        ipv4_address: 172.20.0.7

volumes:
  grafana_data:

networks:
  custom_bridge:
    external: true
