version: '3'

services:
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: postgres
      GF_SECURITY_ADMIN_PASSWORD: postgres
      GF_PROVISIONING_PATH: /etc/grafana/provisioning
    networks:
      raspi_docker_custom_bridge:
        ipv4_address: 188.20.0.11
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      raspi_docker_custom_bridge:
        ipv4_address: 188.20.0.12
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: unless-stopped

  exporter_node:
    image: prom/node-exporter
    container_name: exporter_node
    pid: "host"
    networks:
      raspi_docker_custom_bridge:
        ipv4_address: 188.20.0.13
    volumes:
      - "/:/host:ro,rslave"
    command:
      - '--path.rootfs=/host'
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: loki
    networks:
      raspi_docker_custom_bridge:
        ipv4_address: 188.20.0.14
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki # Persistent storage for log data
      - ./loki/loki.yaml:/etc/loki/loki-config.yaml # Mount the Loki config from host
    command: -config.file=/etc/loki/loki-config.yaml
    environment:
      - LOKI_CONFIG_FILE=/etc/loki/loki-config.yaml

volumes:
  grafana_data:
  prometheus_data:
  tempo_data:
  loki-data:

networks:
  raspi_docker_custom_bridge:
    external: true
