version: '3'
services:
  influxdb:
    image: influxdb:latest
    volumes:
      - influxdb-volume:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=metrics_windows
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    ports:
      - "8086:8086"

volumes:
  influxdb-volume:

networks:
  custom_bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16