receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector-metrics'
          scrape_interval: 5s
          static_configs:
            - targets: ['localhost:8888']
        - job_name: 'prometheus_export'
          scrape_interval: 5s
          static_configs:
            - targets: ['188.20.0.14:9090']

exporters:
  prometheus:
    endpoint: "0.0.0.0:9095" # The endpoint where the Prometheus exporter will serve metrics
    namespace: "exported" # Optional: Prefix for metric names to avoid name clashes
    const_labels: # Optional: Labels to add to all metrics
      from: "exported"


service:
 telemetry:
    logs:
      level: "debug"
    metrics:
      address: localhost:8888
      level: detailed
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [prometheus]
