receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector-metrics'
          scrape_interval: 5s
          static_configs:
            - targets: ['localhost:8888']
        - job_name: 'prometheus_export'
          scrape_interval: 5s
          static_configs:
            - targets: ['188.20.0.14:9090']

exporters:
  prometheusremotewrite:
    endpoint: "http://188.20.0.12:9090/api/v1/write" # Endpoint for prometheus_import
  logging:
    loglevel: debug

service:
 telemetry:
    logs:
      level: "debug"
    metrics:
      address: localhost:8888
      level: detailed

pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [prometheusremotewrite, logging]
