receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector-metrics'
          scrape_interval: 5s
          static_configs:
            - targets: ['0.0.0.0:8888']
        - job_name: 'prometheus_export'
          scrape_interval: 5s
          static_configs:
            - targets: ['prometheus_export:9090']
        - job_name: 'node-exporter'
          scrape_interval: 5s
          static_configs:
            - targets: ['exporter_node:9100']

exporters:
  prometheusremotewrite:
    endpoint: "http://188.20.0.12:9090/api/v1/write" # Endpoint for prometheus_import
  logging:
    loglevel: debug

service:
  pipelines:
      metrics:
        receivers: [prometheus]
        exporters: [prometheusremotewrite, logging]

  telemetry:
    logs:
      level: "debug"
    metrics:
      address: localhost:8888
      level: detailed
