receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'prometheus_export'
          scrape_interval: 5s
          static_configs:
            - targets: ['188.20.0.14:9090']

exporters:
  prometheusremotewrite:
    endpoint: "http://188.20.0.12:9090/api/v1/write"

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [prometheusremotewrite]
