kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

# resources:
#   - ingressRoute.yaml

helmCharts:
  - name: grafana-loki
    version: 4.6.23
    repo: https://charts.bitnami.com/bitnami
    releaseName: loki
    namespace: monitoring
    valuesFile: values.yaml
