kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

# resources:
#   - ingressRoute.yaml
#   - provisioning/datasources.yaml
#   - provisioning/folders.yaml
#   - provisioning/dashboards.yaml

helmCharts:
  - name: opentelemetry-operator
    version: 0.103.0
    repo: https://open-telemetry.github.io/opentelemetry-helm-charts
    releaseName: otel-operator
    namespace: monitoring
    valuesFile: values.yaml
