kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - otel-instance.yaml

helmCharts:
  - name: opentelemetry-operator
    version: 0.74.2
    repo: https://open-telemetry.github.io/opentelemetry-helm-charts
    releaseName: otel-operator
    namespace: monitoring
    valuesFile: values.yaml
