apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "speedtest"
      app.kubernetes.io/instance: "speedtest"
      app.kubernetes.io/version: "0.9.14"
      app.kubernetes.io/component: "speedtest"
      app.kubernetes.io/part-of: "observability"
      app.kubernetes.io/managed-by: "argocd"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "speedtest"
        app.kubernetes.io/instance: "speedtest"
        app.kubernetes.io/version: "0.9.14"
        app.kubernetes.io/component: "speedtest"
        app.kubernetes.io/part-of: "observability"
        app.kubernetes.io/managed-by: "argocd"
      # annotations:
      #   prometheus.io/path: /probe
      #   prometheus.io/port: "9516"
      #   prometheus.io/scrape-slow: "true"
    spec:
      containers:
      - name: speedtest
        image: jraviles/prometheus_speedtest:0.9.14
        imagePullPolicy: Always
        ports:
          - containerPort: 9516
            name: http
            protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 20Mi