apiVersion: v1
kind: Service
metadata:
  name: speedtest
  namespace: monitoring
  labels:
    app.kubernetes.io/name: "speedtest"
    app.kubernetes.io/instance: "speedtest"
    app.kubernetes.io/version: "0.9.14"
    app.kubernetes.io/component: "speedtest"
    app.kubernetes.io/part-of: "observability"
    app.kubernetes.io/managed-by: "argocd"
spec:
  ports:
    - port: 9516
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: "speedtest"
    app.kubernetes.io/instance: "speedtest"
