kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ingressRoute.yaml

helmCharts:
  - name: kube-prometheus-stack
    version: v61.2.0
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: kube-prometheus-stack
    namespace: monitoring
    valuesFile: values.yaml
