apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: operations
  namespace: monitoring
spec:
  title: "operations"
  instanceSelector:
    matchLabels:
      app.kubernetes.io/instance: "grafana-operator"
  allowCrossNamespaceImport: false 
  # permissions: '{"role": "Editor", "permission": "Edit"}'
  resyncPeriod: 5s