apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: monitoring
  labels:
    dashboards: "grafana"
spec:
  version: "11.1.0"
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
    security:
      admin_user: postgres
      admin_password: postgres