apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: grafana
  labels:
    dashboards: "grafana"
spec:
  version: "11.1.0"
  config:
    security:
      admin_user: postgres
      admin_password: postgres