apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus-datasource
  namespace: monitoring
spec:
  datasource:
    name: Prometheus
    type: prometheus
    url: http://prometheus-operated:9090
    access: proxy
    isDefault: true
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
