kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ingressRoute.yaml

helmCharts:
  - name: thanos
    version: 15.8.2
    repo: https://charts.bitnami.com/bitnami
    releaseName: thanos
    namespace: monitoring
    valuesFile: values.yaml
